subdomain_discovery:
    uses_tool: [ amass-passive, subfinder, sublist3r, assetfinder, oneforall ]
    thread: 200

port_scan:
    ports: [ top-100 ]
    thread: 100

visual_identification:
    port: xlarge
    thread: 30
    http_timeout: 3000
    screenshot_timeout: 30000
    scan_timeout: 100

dir_file_search:
    extensions: [ json,config,yml,yaml,bak,log,zip,php,txt,jsp,html,aspx,asp,axd,config,js,xhtml,sql ]
    recursive: false
    recursive_level: 1
    thread: 200
    wordlist: default

fetch_url:
    uses_tool: [ gau, hakrawler ]
    intensity: normal

vulnerability_scan:
    concurrent: 200
    template: [all]
    severity: [critical, high, medium, low, info]
